image: node:20-alpine3.18

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  tags: [rtc]
  script:
    - npm run lint

test:
  stage: test
  tags: [rtc]
  script:
    - npm run test

test_placeholders:
  stage: test
  tags: [rtc]
  script:
    - ./verify-termination-on-placeholders.sh
