image: node:latest

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
