image: node:21-alpine

stages:
  # - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - apk add bash curl jq

# lint:
#   stage: lint
#   tags: [rtc]
#   script:
#     - npm run lint

api:test:
  stage: test
  tags: [rtc]
  script:
    - npm run test

placeholders:test:
  stage: test
  tags: [rtc]
  script:
    - bash -x ./verify-termination-on-placeholders.sh
