include:
  - project: "sinch/sinch-projects/voice/gitlab-pipelines"
    ref: main
    file: "/jobs/_jobs.yml"

default:
  tags: [rtc]

stages:
  # - lint
  - test

cache:
  paths:
    - node_modules/

.node:
  before_script:
    - npm install
    - apk add bash curl jq
  image: public.ecr.aws/docker/library/node:21-alpine
  tags: [rtc]

# lint:
#   stage: lint
#   image: node:21-alpine
#   tags: [rtc]
#   script:
#     - npm run lint

api:test:
  stage: test
  extends: .node
  script:
    - npm run test

placeholders:test:
  stage: test
  extends: .node
  script:
    - bash -x verify-termination-on-placeholders.sh

docker:endpoints:test:
  stage: test
  extends: .kaniko
  variables:
    IMAGE: "sample-oauth-server-for-fcm-v1"
    REPOSITORY: "098456509636.dkr.ecr.eu-central-1.amazonaws.com"
    AWS_ECR_URL: "098456509636.dkr.ecr.eu-central-1.amazonaws.com"
    AWS_DEFAULT_REGION: eu-central-1
  script:
    - echo $CONFIG_JSON_BASE_64 | base64 -d > placeholders/config.json
    - cat placeholders/config.json
    - echo $SERVICE_ACCOUNT_JSON_BASE64 | base64 -d > placeholders/service-account.json
    - !reference [.kaniko, script]
