image: node:21-alpine

stages:
  # - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - apk add bash curl jq

# lint:
#   stage: lint
#   tags: [rtc]
#   script:
#     - npm run lint

api:test:
  stage: test
  tags: [rtc]
  script:
    - npm run test

placeholders:test:
  stage: test
  tags: [rtc]
  script:
    - ./verify-termination-on-placeholders.sh

endpoints:test:
  stage: test
  tags: [docker+machine]
  script:
    - echo $CONFIG_JSON_BASE_64 | base64 -d > placeholders/config.json
    - echo $SERVICE_ACCOUNT_JSON_BASE64 | base64 -d > placeholders/service-account.json
    - docker compose up --build --detach
    - ./test-endpoints-locally.sh
    - docker compose down
